### ISSUE TITLE
Configuring storage credentials outside of transloadit.com

### ISSUE THREAD

**Issue by mfilej** [shrinerb/shrine-transloadit#6]
Hi, I'm migrating to Shrine 3 and I'm having trouble with credentials in the process.

Before the migration I used to define S3 credentials when defining shrine storages:

```ruby
Shrine.storages = {
  store: Shrine::Storage::S3.new(access_key_id: k, secret_access_key: a, region: r, bucket: b),
  cache: …,
}
```

Now with this approach I'm getting an error:
```
Shrine::Plugins::Transloadit::Error (credentials not registered for storage :store)
```

Is this something that is still possible? Having to define the credentials in the web interface on transloadit.com is not ideal from our deployment perspective, so I was wondering if there was a way around this.

**Comment by janko** [comment]
Hmm, I don't remember now why I didn't leave backwards compatibility for sending credentials directly in steps. I will try to address this today and get back to you.

**Comment by janko** [comment]
It will take a bit of work to add back support for directly passing credentials. For now you can work around this by passing `credentials: nil` and passing your own credentials:

```rb
  # somewhere inside `Attacher.transloadit_processor`
  # ...
  export = file.transloadit_export_step(
    credentials:   nil, # tell shrine-transloadit not to require credentials
    bucket:        file.storage.bucket.name,
    bucket_region: file.storage.client.config.region,
    key:           file.storage.client.config.access_key_id,
    secret:        file.storage.client.config.secret_access_key,
  )
  # ...
  export = store.transloadit_export_step(
    credentials:   nil, # tell shrine-transloadit not to require credentials
    bucket:        store.storage.bucket.name,
    bucket_region: store.storage.client.config.region,
    key:           store.storage.client.config.access_key_id,
    secret:        store.storage.client.config.secret_access_key,
  ) 
  # ...
```
