### ISSUE TITLE
Support Transloadit Templates?

### ISSUE THREAD

**Issue by ksouthworth** [shrinerb/shrine-transloadit#8]
Does this plugin support using Transloadit [Templates](https://transloadit.com/docs/#templates) ?

If not, is there a recommended way to get some of the benefits of templates (mainly not having to include sensitive data and credentials inside assembly steps..)

Thanks!

**Comment by ksouthworth** [comment]
Looks like I might be able to just drop into the `transloadit` ruby sdk code and include the `template_id` https://github.com/transloadit/ruby-sdk#4-creating-an-assembly-with-templates

**Comment by janko** [comment]
Yes, in fact, the `Attacher.transloadit_processor` block gives you direct access to the `Transloadit` instance, so you can pass `:template_id` or any other parameters to the assembly.

```rb
 Attacher.transloadit_processor do
    assembly = transloadit.assembly(template_id: "...", **other_params)
    assembly.create!
  end
```
